version: '3'
services:
  web:
    image: mohammad-taradeh/my-static-website:$GIT_VERSION
    ports:
      - "80:80"
    environment:
      - NGINX_ENV=production
    networks:
      - production_network

# networks:
#   production_network:
#     driver: bridge